support baikal, fallback on radicale

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -11,10 +11,24 @@ if [[ ! $? -eq 0 ]]; then
     exit 1
 fi
 
+baikal=0
+radicale=0
+
+sudo yunohost app list --json | grep -q '"id": "baikal"'
+if [[ $? -eq 0 ]]; then
+    baikal=1
+    caldavapp=baikal
+fi
+
 sudo yunohost app list --json | grep -q '"id": "radicale"'
-if [[ ! $? -eq 0 ]]; then
-    echo "Error : Radicale app is not installed"
-    exit 1
+if [[ $? -eq 0 ]]; then
+    radicale=1
+    caldavapp=radicale
+fi
+
+if [ $baikal -eq 0 ] && [ $radicale -eq 0 ]; then
+  echo "Error : You must install Baikal or Radicale before"
+  exit 1
 fi
 
 # Install dependencies
@@ -41,10 +55,17 @@ currentpath=$(pwd)
 cd $final_path/web/application && ln -s ../config config && cd $currentpath
 
 # caldav config
-radicale_path=$(sudo yunohost app setting radicale path)
-radicale_path=${radicale_path%/}
-sed -i "s@YNH_DOMAIN@$domain@g" ../conf/caldav.php
-sed -i "s@YNH_RADICALE_PATH@$radicale_path@g" ../conf/caldav.php
+caldavdomain=$(sudo yunohost app setting $caldavapp domain)
+caldavpath=$(sudo yunohost app setting $caldavapp path)
+if [ $baikal -eq 1 ]; then
+  caldav_principal_url="https://$(caldavdomain)$(caldavpath)/cal.php/%u/"
+  caldav_calendar_url="https://$(caldavdomain)$(caldavpath)/cal.php/calendars/%s/"
+elif [ $radicale -eq 1 ]; then
+  caldav_principal_url="https://$(caldavdomain)$(caldavpath)/%u/"
+  caldav_calendar_url="https://$(caldavdomain)$(caldavpath)/%s/"
+fi
+sed -i "s@YNH_CALDAV_PRINCIPAL_URL@$caldav_principal_url@g" ../conf/caldav.php
+sed -i "s@YNH_CALDAV_CALENDAR_URL@$caldav_calendar_url@g" ../conf/caldav.php
 
 # database config
 sed -i "s/YNH_DB_USER/$db_user/g" ../conf/database.php
